
# @tests src/yuleosh/review/run.py
# Copyright (c) 2025 frisky1985
# SPDX-License-Identifier: Elastic-2.0

"""
Unit tests for yuleosh.pipeline.step_handlers.review_prd — PRD quality review.

Covers the G-50 fix for the PRD review false-negative:
  - Old extractor only recognised `Req-NNN` headings → 0 requirements
    extracted from table-style PRDs (| FR-001 | 描述 | ... |).
  - Old matcher only did ASCII keyword overlap → Chinese PRD text never
    matched English SHALL statements (cross-language false negative).
  - No section-ID alignment: spec `### SR-001` ↔ PRD `### 4.1 (SR-001)`.

Target functions:
  - _extract_shalls
  - _extract_prd_requirements
  - _check_shall_coverage
  - _cjk_tokens
"""


from yuleosh.pipeline.step_handlers.review_prd import (
    _check_shall_coverage,
    _cjk_tokens,
    _extract_prd_requirements,
    _extract_shalls,
)

# ===================================================================
# _extract_shalls
# ===================================================================

class TestExtractShalls:
    def test_basic_list_shall(self):
        spec = (
            "### SR-001: 硬件抽象\n"
            "- The system SHALL provide a HAL abstraction layer\n"
            "- The system SHALL support PWM output\n"
        )
        shalls = _extract_shalls(spec)
        assert len(shalls) == 2
        assert all(s["section"] == "SR-001" for s in shalls)
        assert shalls[0]["kind"] == "SHALL"
        assert "HAL abstraction" in shalls[0]["statement"]

    def test_tracks_multiple_sections(self):
        spec = (
            "### SR-001: A\n"
            "- The system SHALL do A\n"
            "### SW-004: B\n"
            "- The system SHALL do B\n"
        )
        shalls = _extract_shalls(spec)
        assert [s["section"] for s in shalls] == ["SR-001", "SW-004"]

    def test_shall_not_kind(self):
        spec = "- Application modules SHALL NOT access registers\n"
        shalls = _extract_shalls(spec)
        assert len(shalls) == 1
        assert shalls[0]["kind"] == "SHALL NOT"

    def test_no_shall_returns_empty(self):
        assert _extract_shalls("Just some prose without requirements.") == []

    def test_dedup_same_statement(self):
        spec = (
            "- The system SHALL do the thing\n"
            "- The system SHALL do the thing\n"
        )
        assert len(_extract_shalls(spec)) == 1


# ===================================================================
# _extract_prd_requirements
# ===================================================================

class TestExtractPrdRequirements:
    def test_table_style_with_section(self):
        prd = (
            "### 4.1 硬件抽象层 (SR-001)\n\n"
            "| 需求 ID | 描述 | 优先级 | 实现说明 |\n"
            "|---------|------|--------|---------|\n"
            "| FR-001 | 提供电机和霍尔传感器的 HAL 抽象层 | P0 | 定义接口 |\n"
            "| FR-002 | 支持 PWM 输出控制电机速度 | P0 | 线性映射 |\n"
        )
        reqs = _extract_prd_requirements(prd)
        assert len(reqs) == 2
        assert reqs[0]["id"] == "FR-001"
        assert "HAL 抽象层" in reqs[0]["text"]
        assert reqs[0]["section"] == "SR-001"
        assert reqs[1]["section"] == "SR-001"

    def test_header_row_skipped(self):
        prd = (
            "| 需求 ID | 描述 | 优先级 | 实现说明 |\n"
            "|---------|------|--------|---------|\n"
            "| FR-001 | 实际需求 | P0 | note |\n"
        )
        reqs = _extract_prd_requirements(prd)
        assert len(reqs) == 1
        assert reqs[0]["id"] == "FR-001"

    def test_heading_style_requirements(self):
        prd = (
            "### FR-001 手动模式\n"
            "The system SHALL run motor while held\n"
        )
        reqs = _extract_prd_requirements(prd)
        # heading itself contributes one requirement; the SHALL line another
        assert any(r["id"] == "FR-001" for r in reqs)
        assert any("run motor" in r["text"] for r in reqs)

    def test_freeform_keyword_lines(self):
        prd = (
            "### 需求\n"
            "系统必须支持防夹检测\n"
        )
        reqs = _extract_prd_requirements(prd)
        # heading itself is skipped; the free-form line carries 必须/支持
        assert any("防夹" in r["text"] for r in reqs)

    def test_skips_code_blocks_and_quotes(self):
        prd = (
            "> Generated by LLM\n"
            "```\n"
            "| FR-999 | fake table inside code |\n"
            "```\n"
            "| FR-001 | real requirement | P0 | note |\n"
        )
        reqs = _extract_prd_requirements(prd)
        assert len(reqs) == 1
        assert reqs[0]["id"] == "FR-001"

    def test_empty_prd(self):
        assert _extract_prd_requirements("") == []


# ===================================================================
# _cjk_tokens
# ===================================================================

class TestCjkTokens:
    def test_short_run_single_token(self):
        # character-level tokens for "防夹检测"
        tokens = _cjk_tokens("防夹检测")
        assert "防" in tokens
        assert "夹" in tokens
        assert "检" in tokens
        assert "测" in tokens

    def test_long_run_bigrams(self):
        tokens = _cjk_tokens("霍尔传感器脉冲计数")
        assert "霍" in tokens
        assert "传" in tokens
        assert "脉" in tokens

    def test_no_cjk_returns_empty(self):
        assert _cjk_tokens("HAL abstraction layer") == []


# ===================================================================
# _check_shall_coverage
# ===================================================================

SPEC = (
    "### SR-001: 硬件抽象\n"
    "- The system SHALL provide a HAL abstraction layer for window lift motor\n"
    "### SW-004: 防夹检测\n"
    "- The system SHALL detect pinch when motor speed drops below threshold\n"
)

PRD = (
    "### 4.1 硬件抽象层 (SR-001)\n\n"
    "| 需求 ID | 描述 | 优先级 |\n"
    "|---------|------|--------|\n"
    "| FR-001 | 提供电机和霍尔传感器的 HAL 抽象层 | P0 |\n"
    "| FR-002 | 支持 PWM 输出控制电机速度 | P0 |\n"
    "### 4.7 防夹检测 (SW-004)\n\n"
    "| 需求 ID | 描述 | 优先级 |\n"
    "|---------|------|--------|\n"
    "| FR-020 | 速度低于阈值时检测防夹 | P0 |\n"
)


class TestCheckShallCoverage:
    def test_section_alignment_high_confidence(self):
        spec_shalls = _extract_shalls(SPEC)
        prd_reqs = _extract_prd_requirements(PRD)
        findings = _check_shall_coverage(spec_shalls, prd_reqs)
        assert len(findings) == 2
        for f in findings:
            assert f["covered"] is True
            assert f["confidence"] == "high"
            assert f["matched_prd"]

    def test_english_keyword_fallback(self):
        # PRD has no section ID — rely on English keyword overlap
        spec_shalls = _extract_shalls(
            "- The system SHALL provide a HAL abstraction layer for motor\n"
        )
        prd_reqs = [
            {"id": "FR-1", "text": "Provides a HAL abstraction layer for the motor", "section": ""},
        ]
        findings = _check_shall_coverage(spec_shalls, prd_reqs)
        assert findings[0]["covered"] is True
        assert findings[0]["confidence"] == "high"

    def test_cjk_bigram_fallback(self):
        # Chinese spec SHALL (mixed-language spec) matched against Chinese PRD
        spec_shalls = _extract_shalls(
            "- The system SHALL 检测防夹 (detect pinch) when blocked\n"
        )
        prd_reqs = [
            {"id": "FR-1", "text": "检测到障碍物时触发防夹", "section": ""},
        ]
        findings = _check_shall_coverage(spec_shalls, prd_reqs)
        assert findings[0]["covered"] is True

    def test_no_match_none_confidence(self):
        spec_shalls = _extract_shalls(
            "- The system SHALL communicate over CAN bus\n"
        )
        prd_reqs = [
            {"id": "FR-1", "text": "提供座椅加热功能", "section": ""},
        ]
        findings = _check_shall_coverage(spec_shalls, prd_reqs)
        assert findings[0]["covered"] is False
        assert findings[0]["confidence"] == "none"

    def test_may_skipped(self):
        spec_shalls = [{
            "kind": "MAY",
            "statement": "the system may optionally log",
            "line": 1,
            "section": "SR-001",
        }]
        findings = _check_shall_coverage(spec_shalls, [])
        assert findings == []

    def test_full_window_anti_pinch_spec(self):
        """Regression: real window-anti-pinch spec + LLM PRD (table format).

        The old matcher produced 0/56 coverage on this pair; the section-ID
        alignment must lift it well above zero.
        """
        spec = (
            "### SR-001: 硬件抽象\n"
            "- The system SHALL provide a HAL abstraction layer\n"
            "### SW-004: 防夹检测\n"
            "- The system SHALL detect pinch when motor speed drops below threshold\n"
            "- The system SHALL trigger pinch reversal within 50 ms\n"
        )
        prd = (
            "### 4.1 硬件抽象层 (SR-001)\n"
            "| 需求 ID | 描述 | 优先级 |\n"
            "|---------|------|--------|\n"
            "| FR-001 | 提供电机和霍尔传感器的 HAL 抽象层 | P0 |\n"
            "### 4.7 防夹检测 (SW-004)\n"
            "| 需求 ID | 描述 | 优先级 |\n"
            "|---------|------|--------|\n"
            "| FR-020 | 速度低于阈值时检测防夹 | P0 |\n"
            "| FR-021 | 50ms 内触发防夹反转 | P0 |\n"
        )
        spec_shalls = _extract_shalls(spec)
        prd_reqs = _extract_prd_requirements(prd)
        findings = _check_shall_coverage(spec_shalls, prd_reqs)
        assert len(findings) == 3
        assert all(f["covered"] for f in findings)
        assert all(f["confidence"] == "high" for f in findings)
