"""
Pipeline LLM Gateway — unified step-level LLM entry point (方案 C, C4).

All pipeline step LLM calls converge on :func:`call_step_llm`, which:

  a. 组装 role-scoped agent constraints（复用 stages/llm.py 的
     ``_build_effective_system_prompt``，A1-A4 角色隔离不重复实现）；
  b. 通过 ``LLMClient.call_sync``（yuleosh.llm.client）调用统一入口，
     ``task_type`` 由当前步骤的 agent 角色解析（resolve_agent_for_step
     -> resolve_agent_role），返回 content 字符串；
  c. 把 usage 记录到 ``session.token_usage_total`` /
     ``session.token_usage_steps``（OpenAI 风格 usage dict，读
     ``total_tokens``，与既有 step handler 记录格式一致）；
  d. pipeline 总量预算检查：``PIPELINE_TOKEN_BUDGET`` 超限默认只 log
     warning 不阻断；设 ``YULEOSH_PIPELINE_TOKEN_BUDGET_ENFORCE=1`` 时
     抛 ``PipelineStepError`` 阻断；
  e. 任何 LLM 失败统一包装为 ``PipelineStepError``（复用
     yuleosh.pipeline.session.PipelineStepError）。

Mock 模式（``session.mock_mode is True``，严格 ``is True`` 保持
MagicMock session 诚实）：直接返回占位内容，不调 LLM，与现有 --mock
行为一致。

灰度迁移（C5）：stages/llm.py 的 ``_call_llm`` 通过
``YULEOSH_LLM_GATEWAY_STEPS``（逗号分隔 step_key 列表）逐步把步骤切到
本网关，其余步骤保持旧路径。
"""

import logging
import os

from yuleosh.agent_registry import resolve_agent_for_step, resolve_agent_role
from yuleosh.llm.client import LLMClient, resolve_config
from yuleosh.pipeline.session import PipelineSession, PipelineStepError
from yuleosh.pipeline.stages.llm import _build_effective_system_prompt

log = logging.getLogger("pipeline.llm_gateway")

# 全 pipeline token 总量预算（env YULEOSH_PIPELINE_TOKEN_BUDGET 可覆盖）。
PIPELINE_TOKEN_BUDGET = int(os.environ.get("YULEOSH_PIPELINE_TOKEN_BUDGET", "200000"))

# 预算超限是否阻断：默认只 warning；设 "1"/"true" 时抛 PipelineStepError。
_BUDGET_ENFORCE_ENV = "YULEOSH_PIPELINE_TOKEN_BUDGET_ENFORCE"

# Mock 模式占位内容（不调 LLM，与 --mock 既有行为一致）。
MOCK_PLACEHOLDER = (
    "# Mock Response — yuleOSH --mock mode\n\n"
    "This is a mock LLM response generated by the pipeline LLM gateway.\n"
    "The pipeline ran in mock mode — no real LLM was called."
)


def _step_key(session: PipelineSession) -> str:
    """Resolve current step key — thread-local first (D2 parallel), then session.

    并行组执行时 session.pipeline_knowledge_step_key 是共享字段会被并发
    覆盖; orchestrator 在 worker 线程内 set_step_key, 这里优先读它。
    """
    from yuleosh.pipeline.step_context import get_step_key as _tl_step_key

    tl = _tl_step_key()
    if tl:
        return tl
    sk = getattr(session, "pipeline_knowledge_step_key", "") or ""
    return sk if isinstance(sk, str) else ""


def resolve_step_role(session: PipelineSession) -> str | None:
    """Resolve the current step's agent role for ``task_type`` routing.

    Resolution chain: ``session.pipeline_knowledge_step_key`` ->
    ``resolve_agent_for_step`` -> ``resolve_agent_role``.  Returns None
    for unknown steps / non-str keys (callers fall back to defaults).
    """
    step_key = _step_key(session)
    agent = resolve_agent_for_step(step_key)
    return resolve_agent_role(agent) if agent else None


def _budget_enforced() -> bool:
    """Whether budget overrun should hard-fail instead of warning only."""
    return os.environ.get(_BUDGET_ENFORCE_ENV, "").strip().lower() in ("1", "true")


def _check_pipeline_budget(session: PipelineSession) -> None:
    """Pipeline 总量预算检查 — 超限默认只警告；ENFORCE=1 时抛错阻断。"""
    total = getattr(session, "token_usage_total", 0) or 0
    if total <= PIPELINE_TOKEN_BUDGET:
        return
    step_key = _step_key(session)
    log.warning(
        "Pipeline token budget exceeded: %d > %d (step '%s') — continuing "
        "(set %s=1 to enforce)",
        total,
        PIPELINE_TOKEN_BUDGET,
        step_key,
        _BUDGET_ENFORCE_ENV,
    )
    if _budget_enforced():
        raise PipelineStepError(
            f"Pipeline token budget exceeded: {total} > {PIPELINE_TOKEN_BUDGET}"
        )


def _record_usage(session: PipelineSession, usage: dict) -> None:
    """Record one LLM call's usage into the session (OpenAI-style dict)."""
    total = int(usage.get("total_tokens", 0) or 0)
    if total <= 0:
        return
    step_key = _step_key(session)
    if not isinstance(step_key, str) or not step_key:
        step_key = "unknown"
    # D2 (2026-08-19): 线程安全累加 — 并行组多 worker 同时记录。
    session.add_token_usage(step_key, usage)


def call_step_llm(
    session: PipelineSession,
    system_prompt: str,
    user_prompt: str,
    *,
    temperature: float = 0.3,
    max_tokens: int = 4096,
    task_type: str | None = None,
) -> str:
    """Unified per-step LLM entry point (方案 C, C4).

    Args:
        session: Active pipeline session (carries role-scoped constraints,
            knowledge step key, mock flag and token usage accumulators).
        system_prompt: Step system prompt (agent constraints are prepended
            role-scoped by this gateway).
        user_prompt: Step user prompt.
        temperature / max_tokens: LLM call parameters (defaults match
            ``resolve_config`` defaults).
        task_type: Optional explicit task_type override; when None it is
            resolved from the step's agent role.

    Returns:
        The LLM response content (str).

    Raises:
        PipelineStepError: any LLM failure (transport, provider error,
            budget enforce).
    """
    step_key = _step_key(session)

    # Mock 模式：直接返回占位内容，不调 LLM。
    # 严格 `is True` 保持 MagicMock session 诚实（与 mock_skip 一致）。
    if getattr(session, "mock_mode", None) is True:
        log.info("call_step_llm mock mode: placeholder for step '%s'", step_key)
        return MOCK_PLACEHOLDER

    # a. role-scoped agent constraints（A1-A4 角色隔离，复用 stages/llm.py）。
    effective_system = _build_effective_system_prompt(session, system_prompt)

    # b. 统一入口：task_type 从当前步骤 agent 角色解析。
    resolved_task_type = task_type or resolve_step_role(session)
    try:
        config = resolve_config(user_prompt, effective_system, resolved_task_type, None)
        config.temperature = temperature
        config.max_tokens = max_tokens
        result = LLMClient.call_sync(
            prompt=user_prompt,
            system_prompt=effective_system,
            task_type=resolved_task_type,
            config=config,
        )
    except PipelineStepError:
        raise
    except Exception as e:
        raise PipelineStepError(
            f"LLM call failed for step '{step_key}': {e}"
        ) from e

    content = result.get("content", "")

    # c. usage 记录（OpenAI 风格 dict，读 total_tokens）。
    _record_usage(session, result.get("usage") or {})

    # d. pipeline 总量预算检查（超限默认只警告）。
    _check_pipeline_budget(session)

    return content
