"""
Pipeline LLM Gateway — unified step-level LLM entry point (方案 C, C4).

All pipeline step LLM calls converge on :func:`call_step_llm`, which:

  a. 组装 role-scoped agent constraints（复用 stages/llm.py 的
     ``_build_effective_system_prompt``，A1-A4 角色隔离不重复实现）；
  b. 通过 ``LLMClient.call_sync``（yuleosh.llm.client）调用统一入口，
     ``task_type`` 由当前步骤的 agent 角色解析（resolve_agent_for_step
     -> resolve_agent_role），返回 content 字符串；
  c. 把 usage 记录到 ``session.token_usage_total`` /
     ``session.token_usage_steps``（OpenAI 风格 usage dict，读
     ``total_tokens``，与既有 step handler 记录格式一致）；
  d. pipeline 总量预算检查：``PIPELINE_TOKEN_BUDGET`` 超限默认只 log
     warning 不阻断；设 ``YULEOSH_PIPELINE_TOKEN_BUDGET_ENFORCE=1`` 时
     抛 ``PipelineStepError`` 阻断；
  e. 任何 LLM 失败统一包装为 ``PipelineStepError``（复用
     yuleosh.pipeline.session.PipelineStepError）。

Mock 模式（``session.mock_mode is True``，严格 ``is True`` 保持
MagicMock session 诚实）：直接返回占位内容，不调 LLM，与现有 --mock
行为一致。

灰度迁移（C5）：stages/llm.py 的 ``_call_llm`` 通过
``YULEOSH_LLM_GATEWAY_STEPS``（逗号分隔 step_key 列表）逐步把步骤切到
本网关，其余步骤保持旧路径。
"""

import logging
import os

# @req RS-001

from yuleosh.agent_registry import resolve_agent_for_step, resolve_agent_role
from yuleosh.llm.client import LLMClient, resolve_config
from yuleosh.pipeline.session import PipelineSession, PipelineStepError
from yuleosh.pipeline.stages.llm import _build_effective_system_prompt

log = logging.getLogger("pipeline.llm_gateway")

# 全 pipeline token 总量预算（env YULEOSH_PIPELINE_TOKEN_BUDGET 可覆盖）。
PIPELINE_TOKEN_BUDGET = int(os.environ.get("YULEOSH_PIPELINE_TOKEN_BUDGET", "200000"))

# 预算超限是否阻断：默认只 warning；设 "1"/"true" 时抛 PipelineStepError。
_BUDGET_ENFORCE_ENV = "YULEOSH_PIPELINE_TOKEN_BUDGET_ENFORCE"

# Mock 模式占位内容（不调 LLM，与 --mock 既有行为一致）。
MOCK_PLACEHOLDER = (
    "# Mock Response — yuleOSH --mock mode\n\n"
    "This is a mock LLM response generated by the pipeline LLM gateway.\n"
    "The pipeline ran in mock mode — no real LLM was called."
)

# ── H3-2: Auto ChangeSet helpers ─────────────────────────────────────────────

# File extensions whose content LLM steps may write (artifacts + source).
_LLM_ARTIFACT_EXTS = {
    ".md", ".json", ".yaml", ".yml", ".txt",
    ".c", ".h", ".cpp", ".hpp", ".py",
}

# Directories to scan for LLM-writable artifacts (relative to project_dir).
_LLM_SCAN_DIRS = (".yuleosh/artifacts",)


def _capture_llm_changeset(session: PipelineSession) -> dict[str, bytes | None]:
    """Snapshot current LLM artifact files before the LLM step (H3-2a).

    Scans ``.yuleosh/artifacts/`` under ``session.project_dir`` and captures
    the current content of each file whose extension is in
    ``_LLM_ARTIFACT_EXTS``.  Also captures any file paths already registered
    in ``session.artifacts``.

    Returns a ChangeSet dict ``{rel_path: bytes | None}`` where ``None``
    means the file did not exist yet (new file — rollback = delete).
    Non-fatal: returns empty dict on any error.
    """
    from pathlib import Path as _Path

    project_dir = _Path(getattr(session, "project_dir", ".") or ".").resolve()
    changeset: dict[str, bytes | None] = {}

    def _snapshot(path: _Path) -> None:
        try:
            rel = str(path.relative_to(project_dir))
            if path.suffix not in _LLM_ARTIFACT_EXTS:
                return
            if path.exists():
                changeset[rel] = path.read_bytes()
            else:
                changeset[rel] = None
        except (ValueError, OSError):
            pass

    # Scan standard artifact dirs
    for scan_rel in _LLM_SCAN_DIRS:
        scan_dir = project_dir / scan_rel
        if scan_dir.is_dir():
            for p in scan_dir.rglob("*"):
                if p.is_file():
                    _snapshot(p)

    # Also capture registered session artifacts
    for path_str in (session.artifacts or {}).values():
        if isinstance(path_str, str):
            _snapshot(_Path(path_str))

    return changeset


def _restore_llm_changeset(
    session: PipelineSession,
    changeset: dict[str, bytes | None],
) -> None:
    """Restore artifact files from a previously captured ChangeSet (H3-2b).

    Non-fatal: logs warnings on individual file errors and continues.
    """
    from pathlib import Path as _Path

    if not changeset:
        return
    project_dir = _Path(getattr(session, "project_dir", ".") or ".").resolve()
    restored = 0
    for rel, orig in changeset.items():
        dst = project_dir / rel
        try:
            if orig is None:
                # File was new — delete it on rollback
                if dst.exists():
                    dst.unlink()
            else:
                dst.parent.mkdir(parents=True, exist_ok=True)
                dst.write_bytes(orig)
            restored += 1
        except OSError as e:
            log.warning("ChangeSet restore failed for '%s': %s", rel, e)
    log.info("ChangeSet restore: %d/%d file(s) restored", restored, len(changeset))


def _step_key(session: PipelineSession) -> str:
    """Resolve current step key — thread-local first (D2 parallel), then session.

    并行组执行时 session.pipeline_knowledge_step_key 是共享字段会被并发
    覆盖; orchestrator 在 worker 线程内 set_step_key, 这里优先读它。
    """
    from yuleosh.pipeline.step_context import get_step_key as _tl_step_key

    tl = _tl_step_key()
    if tl:
        return tl
    sk = getattr(session, "pipeline_knowledge_step_key", "") or ""
    return sk if isinstance(sk, str) else ""


def resolve_step_role(session: PipelineSession) -> str | None:
    """Resolve the current step's agent role for ``task_type`` routing.

    Resolution chain: ``session.pipeline_knowledge_step_key`` ->
    ``resolve_agent_for_step`` -> ``resolve_agent_role``.  Returns None
    for unknown steps / non-str keys (callers fall back to defaults).
    """
    step_key = _step_key(session)
    agent = resolve_agent_for_step(step_key)
    return resolve_agent_role(agent) if agent else None


def _budget_enforced() -> bool:
    """Whether budget overrun should hard-fail instead of warning only."""
    return os.environ.get(_BUDGET_ENFORCE_ENV, "").strip().lower() in ("1", "true")


def _check_pipeline_budget(session: PipelineSession) -> None:
    """Pipeline 总量预算检查 — 超限默认只警告；ENFORCE=1 时抛错阻断。"""
    total = getattr(session, "token_usage_total", 0) or 0
    if total <= PIPELINE_TOKEN_BUDGET:
        return
    step_key = _step_key(session)
    log.warning(
        "Pipeline token budget exceeded: %d > %d (step '%s') — continuing "
        "(set %s=1 to enforce)",
        total,
        PIPELINE_TOKEN_BUDGET,
        step_key,
        _BUDGET_ENFORCE_ENV,
    )
    if _budget_enforced():
        raise PipelineStepError(
            f"Pipeline token budget exceeded: {total} > {PIPELINE_TOKEN_BUDGET}"
        )


def _record_usage(session: PipelineSession, usage: dict) -> None:
    """Record one LLM call's usage into the session (OpenAI-style dict)."""
    total = int(usage.get("total_tokens", 0) or 0)
    if total <= 0:
        return
    step_key = _step_key(session)
    if not isinstance(step_key, str) or not step_key:
        step_key = "unknown"
    # D2 (2026-08-19): 线程安全累加 — 并行组多 worker 同时记录。
    session.add_token_usage(step_key, usage)


# ── H3-1b: confidence self-report instruction ────────────────────────────────
# Module-level switch: when disabled, the CONFIDENCE: instruction block is not
# appended to the effective system prompt (callers/tests that need strict
# prompt passthrough can turn it off).
CONFIDENCE_INSTRUCTION_ENABLED = True


def call_step_llm(
    session: PipelineSession,
    system_prompt: str,
    user_prompt: str,
    *,
    temperature: float = 0.3,
    max_tokens: int = 4096,
    task_type: str | None = None,
) -> str:
    """Unified per-step LLM entry point (方案 C, C4).

    Args:
        session: Active pipeline session (carries role-scoped constraints,
            knowledge step key, mock flag and token usage accumulators).
        system_prompt: Step system prompt (agent constraints are prepended
            role-scoped by this gateway).
        user_prompt: Step user prompt.
        temperature / max_tokens: LLM call parameters (defaults match
            ``resolve_config`` defaults).
        task_type: Optional explicit task_type override; when None it is
            resolved from the step's agent role.

    Returns:
        The LLM response content (str).

    Raises:
        PipelineStepError: any LLM failure (transport, provider error,
            budget enforce).
    """
    step_key = _step_key(session)

    # Mock 模式：直接返回占位内容，不调 LLM。
    # 严格 `is True` 保持 MagicMock session 诚实（与 mock_skip 一致）。
    if getattr(session, "mock_mode", None) is True:
        log.info("call_step_llm mock mode: placeholder for step '%s'", step_key)
        return MOCK_PLACEHOLDER

    # H3-2a: capture artifact snapshot before LLM call for auto-rollback.
    _changeset: dict = {}
    try:
        _changeset = _capture_llm_changeset(session)
        log.debug(
            "ChangeSet captured: %d file(s) for step '%s'",
            len(_changeset), step_key,
        )
    except Exception as _ce:  # noqa: BLE001
        log.debug("ChangeSet capture failed (non-fatal): %s", _ce)

    # a. role-scoped agent constraints（A1-A4 角色隔离，复用 stages/llm.py）。
    effective_system = _build_effective_system_prompt(session, system_prompt)

    # H3-1b: append confidence self-report instruction to all gateway steps.
    if CONFIDENCE_INSTRUCTION_ENABLED:
        effective_system = (
            effective_system
            + "\n\n[Confidence Instruction]\n"
            "At the end of your response, append a single line:\n"
            "CONFIDENCE: <value>\n"
            "where <value> is a float between 0.0 (completely uncertain) and "
            "1.0 (fully certain) reflecting your overall confidence in the "
            "accuracy and grounding of this output. Do not skip this line."
        )

    # b. 统一入口：task_type 从当前步骤 agent 角色解析。
    resolved_task_type = task_type or resolve_step_role(session)
    try:
        config = resolve_config(user_prompt, effective_system, resolved_task_type, None)
        config.temperature = temperature
        config.max_tokens = max_tokens
        result = LLMClient.call_sync(
            prompt=user_prompt,
            system_prompt=effective_system,
            task_type=resolved_task_type,
            config=config,
        )
    except PipelineStepError:
        # H3-2b: restore artifact snapshot on LLM step failure.
        if _changeset:
            try:
                _restore_llm_changeset(session, _changeset)
            except Exception as _re:  # noqa: BLE001
                log.warning("ChangeSet restore failed (non-fatal): %s", _re)
        raise
    except Exception as e:
        # H3-2b: restore artifact snapshot on unexpected failure.
        if _changeset:
            try:
                _restore_llm_changeset(session, _changeset)
            except Exception as _re:  # noqa: BLE001
                log.warning("ChangeSet restore failed (non-fatal): %s", _re)
        raise PipelineStepError(
            f"LLM call failed for step '{step_key}': {e}"
        ) from e

    content = result.get("content", "")

    # H3-1c: extract and strip the CONFIDENCE: line from the LLM output.
    # Store parsed confidence on session for H3-1d gate triage.
    try:
        from yuleosh.llm.fallback import _extract_confidence
        content, _confidence = _extract_confidence(content)
        session.last_confidence = _confidence
        if _confidence is not None:
            log.debug(
                "Confidence for step '%s': %.2f", step_key, _confidence
            )
            # H3-1d: confidence < 0.5 → flag for human review
            if _confidence < 0.5:
                log.warning(
                    "Low confidence (%.2f < 0.5) for step '%s' — "
                    "flagged for human review",
                    _confidence, step_key,
                )
                session.last_confidence_flag = "needs_human_review"
            else:
                session.last_confidence_flag = None
    except Exception as _e:  # noqa: BLE001
        log.debug("Confidence extraction failed (non-fatal): %s", _e)

    # c. usage 记录（OpenAI 风格 dict，读 total_tokens）。
    _record_usage(session, result.get("usage") or {})

    # d. pipeline 总量预算检查（超限默认只警告）。
    _check_pipeline_budget(session)

    # e. Source grounding check (H2-1c) — non-fatal annotation pass.
    # Validates file:line / function / requirement references in the output.
    # Report is stored on the session for gate evaluation; never blocks.
    try:
        from yuleosh.pipeline.source_grounding import SourceGroundingChecker
        from yuleosh.pipeline.repo_facts import (
            get_all_function_names,
            get_all_requirement_ids,
        )

        source_files = getattr(session, "injected_source_files", None) or []
        project_dir = getattr(session, "project_dir", None)
        func_names: set[str] = set()
        req_ids: set[str] = set()
        if project_dir:
            try:
                func_names = get_all_function_names(project_dir)
                req_ids = get_all_requirement_ids(project_dir)
            except Exception as _e:
                log.debug("repo_facts extraction failed (non-fatal): %s", _e)

        checker = SourceGroundingChecker(
            source_files=source_files,
            known_function_names=func_names if func_names else None,
            known_req_ids=req_ids if req_ids else None,
        )
        report = checker.check(content)
        session.last_grounding_report = report.to_dict()
        if not report.clean:
            log.warning(
                "Source grounding: %d violation(s) in step '%s' output",
                report.to_dict()["violation_count"],
                step_key,
            )
    except Exception as _e:  # noqa: BLE001
        log.debug("Source grounding check failed (non-fatal): %s", _e)

    return content
