#!/usr/bin/env python3
# Copyright (c) 2025 frisky1985
# SPDX-License-Identifier: Elastic-2.0

"""
Analysis step handlers — S.U.P.E.R analysis, PRD generation, internal review.

Exports:
  step_super_analysis — AI-powered S.U.P.E.R startup analysis
  step_hermes_prd     — AI-powered product requirements document generation
  step_internal_review — AI-powered internal review of artifacts
"""

import json
import logging
import re
from datetime import UTC, datetime
from pathlib import Path

from yuleosh.pipeline.session import PipelineSession, PipelineStepError
from yuleosh.pipeline.stages import timed_step, _call_llm, _parse_spec
from yuleosh.pipeline.prompts import (
    build_super_analysis_prompt,
    build_prd_prompt,
    build_internal_review_prompt,
)

log = logging.getLogger("pipeline.step_handlers.analysis")

__all__ = ["step_super_analysis", "step_hermes_prd", "step_internal_review"]


# ------------------------------------------------------------------
# PRD section coverage guard (2026-08-13)
# ------------------------------------------------------------------

# Spec section IDs that the PRD must cover: `### SR-001`, `### SW-004`
_SPEC_SECTION_ID_RE = re.compile(r"^#{2,4}\s+([A-Z]{2}-\d+)\b", re.IGNORECASE)
# PRD section heading carrying a spec ID: `### 4.1 硬件抽象层 (SR-001)`
_PRD_COVERED_SECTION_RE = re.compile(r"\(?([A-Z]{2}-\d+)\)?", re.IGNORECASE)


def _check_prd_section_coverage(spec_content: str, prd_content: str) -> list[str]:
    """Return spec section IDs (SR-XXX/SW-XXX) missing from the PRD.

    A section is *covered* when the PRD carries the same section ID anywhere
    (heading or body). Spec sections are gathered from `### SR-XXX:` headings;
    scenario headings (`### Scenario:`) are not requirement sections.
    """
    if not spec_content or not prd_content:
        return []
    spec_sections: list[str] = []
    for line in spec_content.splitlines():
        m = _SPEC_SECTION_ID_RE.match(line.strip())
        if m:
            sid = m.group(1).upper()
            if sid not in spec_sections:
                spec_sections.append(sid)
    if not spec_sections:
        return []

    prd_upper = prd_content.upper()
    missing = [sid for sid in spec_sections if sid not in prd_upper]
    return missing


def _prd_retry_prompt(original_user_prompt: str, missing_sections: list[str]) -> str:
    """Build a retry prompt feeding the missing section list back to the LLM."""
    return (
        original_user_prompt
        + "\n\n"
        + "## ⚠️ Coverage feedback from automated review\n"
        + "Your previous PRD did NOT cover the following spec section(s): "
        + ", ".join(missing_sections)
        + ".\n"
        + "Please revise the PRD so that EVERY one of these sections has a "
        + "corresponding Functional Requirements subsection with a heading that "
        + "keeps the section ID in parentheses (e.g. `### 4.x 名称 (SR-001)`), "
        + "each expressed as table rows (FR-NNN). Do not omit any section.\n"
    )


@timed_step
def step_super_analysis(session: PipelineSession) -> str:
    """Step 1: 小明 — S.U.P.E.R analysis powered by real LLM."""
    try:
        print("  📊 [小明] Running AI-powered S.U.P.E.R analysis...")
        log.info("Running AI-powered S.U.P.E.R analysis")

        spec_path = Path(session.spec_path)
        spec_content = spec_path.read_text() if spec_path.exists() else "(spec file not found)"
        parsed = _parse_spec(session.spec_path)
        requirements = parsed["requirements"]
        scenarios = parsed["scenarios"]
        total_shall = sum(len(r.get("shall_statements", [])) for r in requirements)

        system_prompt, user_prompt = build_super_analysis_prompt(
            spec_content=spec_content,
            spec_name=spec_path.name,
            requirements=requirements,
            scenarios=scenarios,
        )

        try:
            result = _call_llm(session, system_prompt, user_prompt)
        except Exception as e:
            log.error(f"LLM call failed during S.U.P.E.R analysis: {e}")
            raise PipelineStepError(
                f"S.U.P.E.R analysis LLM call failed: {e}\n"
                f"Spec: {session.spec_path}\n"
                f"This error is not silently degraded \u2014 the pipeline stops here."
            )

        analysis = result["content"]
        usage = result.get("usage", {})
        log.info(
            "LLM returned %d tokens (prompt=%s, completion=%s)",
            usage.get("total_tokens", "?"),
            usage.get("prompt_tokens", "?"),
            usage.get("completion_tokens", "?"),
        )
        session.token_usage_total += usage.get("total_tokens", 0)
        session.token_usage_steps.append({"step": "super-analysis", "usage": usage})

        # Prepend a metadata header
        full_output = (
            f"# S.U.P.E.R Analysis: {Path(session.spec_path).stem}\n\n"
            f"> Source spec: {session.spec_path}\n"
            f"> Generated by: LLM ({result.get('model', 'unknown')})\n"
            f"> Requirements: {len(requirements)}  |  SHALLs: {total_shall}  |  Scenarios: {len(scenarios)}\n"
            f"> Tokens: {usage.get('total_tokens', '?')} (prompt {usage.get('prompt_tokens', '?')} + completion {usage.get('completion_tokens', '?')})\n\n"
            f"{analysis}"
        )

        out_path = session.session_dir / "startup-analysis.md"
        try:
            out_path.write_text(full_output)
        except OSError as e:
            log.error(f"Cannot write analysis file: {e}")
            raise PipelineStepError(f"Cannot write analysis file: {e}")
        print(f"  ✅ [小明] AI S.U.P.E.R analysis generated at {out_path}")
        log.info(f"AI S.U.P.E.R analysis saved to {out_path}")
        return str(out_path)
    except PipelineStepError:
        raise
    except Exception as e:
        log.error(f"S.U.P.E.R analysis failed: {e}")
        raise PipelineStepError(f"S.U.P.E.R analysis failed: {e}")


@timed_step
def step_hermes_prd(session: PipelineSession) -> str:
    """Step 2: Hermes — AI-powered PRD generation from spec.

    Reads the spec file, parses requirements and scenarios,
    then uses the LLM to produce a real Product Requirements Document.

    Quality guard (2026-08-13): after each LLM generation the PRD is checked
    for spec-section coverage (SR-XXX / SW-XXX alignment). Missing sections
    trigger a bounded retry (max 2) with the missing list fed back to the LLM.
    If the retries are exhausted, the PRD is still written (best effort) and
    the missing sections are recorded in a sidecar report — the step does NOT
    fabricate template content or silently pass.
    """
    try:
        print("  🔮 [Hermes] Running AI-powered PRD generation...")
        log.info("Running AI-powered PRD generation")

        spec_path = Path(session.spec_path)
        spec_content = spec_path.read_text() if spec_path.exists() else "(spec file not found)"
        parsed = _parse_spec(session.spec_path)
        requirements = parsed["requirements"]
        scenarios = parsed["scenarios"]
        total_shall = sum(len(r.get("shall_statements", [])) for r in requirements)

        # Read S.U.P.E.R analysis from artifacts if available
        super_content = ""
        super_key = "super-analysis"
        if super_key in session.artifacts:
            super_path = Path(session.artifacts[super_key])
            if super_path.exists():
                super_content = super_path.read_text()

        system_prompt, user_prompt = build_prd_prompt(
            spec_content=spec_content,
            spec_name=Path(session.spec_path).name,
            requirements=requirements,
            scenarios=scenarios,
            super_analysis_content=super_content,
        )

        max_retries = 2
        result: dict | None = None
        missing_sections: list[str] = []
        for attempt in range(max_retries + 1):
            try:
                result = _call_llm(session, system_prompt, user_prompt)
            except Exception as e:
                log.error(f"LLM call failed during PRD generation: {e}")
                raise PipelineStepError(
                    f"PRD generation LLM call failed: {e}\n"
                    f"Spec: {session.spec_path}"
                )

            analysis = result["content"]
            # ── Section coverage check (best effort, only after first pass) ──
            missing_sections = _check_prd_section_coverage(spec_content, analysis)
            if not missing_sections:
                break
            if attempt < max_retries:
                log.warning(
                    "PRD missing %d spec section(s): %s — retry %d/%d",
                    len(missing_sections), ", ".join(missing_sections),
                    attempt + 1, max_retries,
                )
                user_prompt = _prd_retry_prompt(user_prompt, missing_sections)

        assert result is not None, "PRD LLM call did not return a result"
        usage = result.get("usage", {})
        log.info(
            "LLM returned %d tokens (prompt=%s, completion=%s)",
            usage.get("total_tokens", "?"),
            usage.get("prompt_tokens", "?"),
            usage.get("completion_tokens", "?"),
        )
        session.token_usage_total += usage.get("total_tokens", 0)
        session.token_usage_steps.append({"step": "prd", "usage": usage})

        full_output = (
            f"# PRD: {session.name}\n\n"
            f"> Generated from spec: {session.spec_path}\n"
            f"> Generated by: LLM ({result.get('model', 'unknown')})\n"
            f"> Requirements: {len(requirements)}  |  SHALLs: {total_shall}  |  Scenarios: {len(scenarios)}\n"
            f"> Tokens: {usage.get('total_tokens', '?')} (prompt {usage.get('prompt_tokens', '?')} + completion {usage.get('completion_tokens', '?')})\n\n"
            f"{analysis}"
        )

        out_path = session.session_dir / "prd.md"
        try:
            out_path.write_text(full_output)
        except OSError as e:
            log.error(f"Cannot write PRD: {e}")
            raise PipelineStepError(f"Cannot write PRD: {e}")

        # ── Sidecar coverage report (never silently pass) ──
        if missing_sections:
            cov_report = {
                "session": session.name,
                "timestamp": datetime.now(UTC).isoformat(),
                "status": "partial",
                "missing_spec_sections": missing_sections,
                "message": (
                    f"PRD written but missing {len(missing_sections)} spec section(s). "
                    "Review and extend the PRD before release."
                ),
            }
            try:
                cov_path = session.session_dir / "prd-coverage-gap.json"
                cov_path.write_text(json.dumps(cov_report, indent=2, ensure_ascii=False))
                log.warning("PRD coverage gap report written to %s", cov_path)
            except OSError as e:
                log.warning("Cannot write PRD coverage gap report: %s", e)

        print(f"  ✅ [Hermes] AI-powered PRD generated at {out_path}"
              + (f" (⚠️ missing {len(missing_sections)} section(s): {', '.join(missing_sections)})" if missing_sections else ""))
        log.info(f"AI-powered PRD saved to {out_path}")
        return str(out_path)
    except PipelineStepError:
        raise
    except Exception as e:
        log.error(f"PRD step failed: {e}")
        raise PipelineStepError(f"PRD step failed: {e}")


@timed_step
def step_internal_review(session: PipelineSession) -> str:
    """Step 3: 小明 — AI-powered internal review.

    Checks artifact existence (hard requirement) then uses LLM to assess
    quality, consistency, and traceability of generated artifacts.
    """
    try:
        print("  🔍 [小明] Running AI-powered internal review...")
        log.info("Running internal review")

        artifacts = session.artifacts

        # Check required artifacts exist (hard requirement)
        required = ["spec-check", "super-analysis", "prd"]
        missing = [r for r in required if r not in artifacts]
        if missing:
            log.error(f"Internal review failed \u2014 missing artifacts: {', '.join(missing)}")
            raise PipelineStepError(
                f"Internal review failed \u2014 missing artifacts: {', '.join(missing)}"
            )

        # Read artifact summaries for LLM analysis
        artifact_summaries: dict[str, str] = {}
        for key, path in artifacts.items():
            try:
                p = Path(path)
                if p.exists():
                    content = p.read_text()[:300]
                    first_line = content.split("\n", 1)[0].strip("# ").strip()
                    artifact_summaries[key] = first_line or "(empty)"
                else:
                    artifact_summaries[key] = "MISSING"
            except Exception:
                artifact_summaries[key] = "(read error)"

        # Read spec for context
        spec_path = Path(session.spec_path)
        spec_content = spec_path.read_text() if spec_path.exists() else "(spec file not found)"

        system_prompt, user_prompt = build_internal_review_prompt(
            session_name=session.name,
            spec_content=spec_content,
            spec_name=spec_path.name,
            artifact_paths=session.artifacts,
            artifact_summaries=artifact_summaries,
        )

        try:
            result = _call_llm(session, system_prompt, user_prompt, max_tokens=2048)
            analysis = result["content"]
            usage = result.get("usage", {})
            log.info(
                "LLM returned %d tokens for internal review (prompt=%s, completion=%s)",
                usage.get("total_tokens", "?"),
                usage.get("prompt_tokens", "?"),
                usage.get("completion_tokens", "?"),
            )
            session.token_usage_total += usage.get("total_tokens", 0)
            session.token_usage_steps.append({"step": "internal-review", "usage": usage})

            full_output = (
                f"# Internal Review: {session.name}\n\n"
                f"> Generated by: LLM ({result.get('model', 'unknown')})\n"
                f"> Tokens: {usage.get('total_tokens', '?')} "
                f"(prompt {usage.get('prompt_tokens', '?')} + "
                f"completion {usage.get('completion_tokens', '?')})\n\n"
                f"{analysis}"
            )
        except (RuntimeError, PipelineStepError) as llm_err:
            # Fallback to basic report if LLM fails
            log.warning(f"LLM call for internal review failed, using basic template: {llm_err}")
            lines = [
                f"# Internal Review: {session.name}",
                f"",
                f"> ⚠\ufe0f AI-powered analysis unavailable \u2014 LLM call failed",
                f"",
                f"## Artifact Status",
                f"",
            ]
            for key, path in session.artifacts.items():
                p = Path(path)
                if p.exists():
                    lines.append(f"\u2705 **{key}**: `{path}`")
                else:
                    lines.append(f"\u274c **{key}**: MISSING at `{path}`")
            full_output = "\n".join(lines)

        out_path = session.session_dir / "review-result.md"
        try:
            out_path.write_text(full_output)
        except OSError as e:
            log.error(f"Cannot write review result: {e}")
            raise PipelineStepError(f"Cannot write review result: {e}")
        print(f"  ✅ [小明] AI internal review generated at {out_path}")
        log.info("Internal review passed")
        return str(out_path)
    except PipelineStepError:
        raise
    except Exception as e:
        log.error(f"Internal review failed: {e}")
        raise PipelineStepError(f"Internal review failed: {e}")
