/**
 * @file Rte_App.h
 * @brief RTE header stub — generated by RTE generator from SW-C ARXML.
 *
 * This file is a placeholder demonstrating the AUTOSAR RTE interface.
 * In a production workflow, this file would be auto-generated by
 * the yuleASR RTE generator from ARXML SW-C descriptors.
 */

#ifndef RTE_APP_H
#define RTE_APP_H

#include "Std_Types.h"
#include "Com.h"

/* ─── Port Prototypes (RTE API) ───────────────────────────── */

#define RTE_E_OK      0U
#define RTE_E_NOT_OK  1U

/* SR Port: AppInput → Sender */
extern Std_ReturnType Rte_Read_AppInput_Command(uint8_t *value);

/* SR Port: AppOutput → Receiver */
extern Std_ReturnType Rte_Write_AppOutput_State(uint16_t value);

/* CS Port: AppDiag */
extern Std_ReturnType Rte_Call_AppDiag_App_DiagnosticService(
    uint8_t serviceId,
    const uint8_t *data,
    uint16_t length);

/* ─── Stub implementations (placeholder) ──────────────────── */

static inline Std_ReturnType Rte_Read_AppInput_Command(uint8_t *value)
{
    if (value != NULL_PTR)
    {
        *value = 0U;
        return RTE_E_OK;
    }
    return RTE_E_NOT_OK;
}

static inline Std_ReturnType Rte_Write_AppOutput_State(uint16_t value)
{
    /* Would normally route via Com_IPduGroup / Com_SendSignal */
    (void)value;
    return RTE_E_OK;
}

static inline Std_ReturnType Rte_Call_AppDiag_App_DiagnosticService(
    uint8_t serviceId,
    const uint8_t *data,
    uint16_t length)
{
    /* Would route via RTE to the SW-C implementation */
    (void)serviceId;
    (void)data;
    (void)length;
    return RTE_E_OK;
}

#endif /* RTE_APP_H */
