# Copyright (c) 2025 frisky1985
# SPDX-License-Identifier: Elastic-2.0

"""RTE (Run-Time Environment) code generator for AUTOSAR SWC components.

Wraps the existing ARXML parser + StubGenerator (``yuleosh.autosar.stubgen``)
to produce RTE stub/mock C sources for parsed SWC components. Invoked by
``pipeline/async_runner.py`` Stage 3 (RTE Generate).

Previously this was a dangling import (the module did not exist) and Stage 3
silently fell back to mock files. This module makes Stage 3 produce real RTE
stubs when an ARXML is supplied, while keeping the mock fallback for demos.
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Dict, List, Optional

logger = logging.getLogger("autosar.rte_generator")


def generate(
    output_dir: str,
    arxml_path: Optional[str] = None,
    config_path: Optional[str] = None,
) -> Dict[str, object]:
    """Generate RTE stub code for the given ARXML.

    Args:
        output_dir: Directory to write generated RTE files into.
        arxml_path: Path to the ARXML describing SWC components. When None or
            missing, minimal mock RTE files are emitted (demo fallback).
        config_path: Optional JSON config (reserved; currently unused).

    Returns:
        ``{"files": [generated file paths]}`` — matches the async_runner
        Stage 3 contract (``output.get("files", [])``).
    """
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)

    if arxml_path and Path(arxml_path).exists():
        try:
            from yuleosh.autosar.parser import ARXMLParser
            from yuleosh.autosar.stubgen import StubGenerator

            parser = ARXMLParser()
            swcs = parser.parse_swc(arxml_path)
            if not swcs:
                logger.warning("ARXML %s contained no SWC components", arxml_path)
            else:
                generator = StubGenerator(project_dir=str(out))
                results = generator.generate_all(swcs)
                files: List[str] = []
                for module in results.values():
                    if getattr(module, "header_path", None):
                        files.append(str(module.header_path))
                    if getattr(module, "source_path", None):
                        files.append(str(module.source_path))
                logger.info(
                    "RTE generated %d stub file(s) from %s", len(files), arxml_path
                )
                return {"files": files}
        except Exception as exc:  # noqa: BLE001 — never crash the pipeline stage
            logger.warning("RTE generation failed (%s); using mock fallback", exc)

    # Fallback: no ARXML (or generation failed) → emit minimal mock RTE sources.
    logger.info("Emitting mock RTE files in %s", out)
    (out / "Rte.c").write_text("// RTE generated by yuleOSH\n")
    (out / "Rte.h").write_text("// RTE header generated by yuleOSH\n")
    (out / "Rte_Swc.h").write_text("// SWC header generated by yuleOSH\n")
    return {
        "files": [
            str(out / "Rte.c"),
            str(out / "Rte.h"),
            str(out / "Rte_Swc.h"),
        ]
    }
