# Copyright (c) 2025 frisky1985
# SPDX-License-Identifier: MIT

"""
AUTOSAR Phase 2 — RTE Stub/Mock Code Generator

Generates C stub/mock functions based on parsed AUTOSAR SWC descriptors.
Reads RTE configuration (SWC ports, runnables, interfaces) and produces:

  - Stub C source files (.c / .h) for every RunnableEntity
  - Mock implementations for RTE read/write primitives
  - Test harness skeleton that can be compiled with Unity/CMock

Design goals:

  1. Zero-config: given an ARXML file, produce compilable stubs.
  2. Minimal coupling: stubs depend only on the SWC interface contract,
     not on a full RTE implementation.
  3. ASPICE-aligned: stubs serve as integration test doubles for SWE.5
     (Software Integration and Verification).

Usage::

    from yuleosh.autosar.stubgen import StubGenerator

    gen = StubGenerator(project_dir="output/stubs")
    gen.generate(swc)          # Generate all stubs for one SWC
    gen.generate_all(swcs)     # Generate stubs for multiple SWCs
"""

from __future__ import annotations

import logging
import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Dict, List, Optional, Set

from yuleosh.autosar.models import (
    PortPrototype,
    RunnableEntity,
    SWCComponent,
    SwcInternalBehavior,
)

log = logging.getLogger("autosar.stubgen")

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

HEADER_GUARD_TEMPLATE = "{name}_STUB_H_"
RTE_PREFIX = "Rte_"

# Default stub output structure
DEFAULT_SWC_DIR = "swc"
DEFAULT_TEST_DIR = "test"
DEFAULT_MOCK_DIR = "mocks"

# RTE primitive macros
RTE_READ_MACRO = "Rte_Read"
RTE_WRITE_MACRO = "Rte_Write"
RTE_INVOKE_MACRO = "Rte_Call"

# Standard RTE include
RTE_HEADER = '"Rte_Type.h"'

# License header
LICENSE_BLOCK = """/*
 * Copyright (c) 2025 frisky1985
 * SPDX-License-Identifier: MIT
 *
 * AUTOGENERATED FILE — DO NOT EDIT
 * Generated by yuleOSH AUTOSAR Stub Generator
 * Source: {source}
 * Generated at: {timestamp}
 */
"""

INIT_VALUE_MAP: dict = {
    "uint8": "0U",
    "uint16": "0U",
    "uint32": "0UL",
    "uint64": "0ULL",
    "sint8": "0",
    "sint16": "0",
    "sint32": "0L",
    "sint64": "0LL",
    "float32": "0.0F",
    "float64": "0.0",
    "boolean": "FALSE",
}


# ---------------------------------------------------------------------------
#  Stub data models
# ---------------------------------------------------------------------------


@dataclass
class StubFunction:
    """Descriptor for a generated stub function."""

    name: str
    """C function name."""

    return_type: str = "void"
    """Return type (default void)."""

    params: List[str] = field(default_factory=list)
    """Parameter declarations (e.g., ['uint8 value', 'const uint8* data'])."""

    call_counter: bool = True
    """Whether to emit a call counter for test assertions."""

    mock_return: bool = False
    """Whether to support mocking the return value."""

    body_lines: List[str] = field(default_factory=list)
    """Custom body lines (if any). Otherwise defaults are generated."""

    comment: str = ""
    """Doxygen-style comment for the function."""

    is_rte_primitive: bool = False
    """Whether this is an RTE primitive (Rte_Read/Rte_Write)."""


@dataclass
class StubModule:
    """A generated stub module (one per SWC)."""

    swc_name: str
    """SWC short name."""

    header_path: str
    """Relative path to the generated header."""

    source_path: str
    """Relative path to the generated source."""

    functions: List[StubFunction] = field(default_factory=list)
    """Stub functions in this module."""

    global_vars: List[str] = field(default_factory=list)
    """Global variable declarations (for call counters, mock returns)."""

    includes: List[str] = field(default_factory=list)
    """Additional include directives."""

    rte_reads: List[str] = field(default_factory=list)
    """RTE read port names (for mock setup)."""

    rte_writes: List[str] = field(default_factory=list)
    """RTE write port names (for mock assertions)."""


# ---------------------------------------------------------------------------
#  Stub Generator
# ---------------------------------------------------------------------------


class StubGenerator:
    """Generates C stub/mock files for AUTOSAR SWC components.

    Args:
        project_dir: Root output directory for generated stubs.
        rte_header: RTE header to include (default "Rte_Type.h").
        emit_call_counters: Whether to emit call counters for test assertions.
        emit_mock_returns: Whether to emit mock return value infrastructure.
    """

    def __init__(
        self,
        project_dir: str = "generated/stubs",
        rte_header: str = '"Rte_Type.h"',
        emit_call_counters: bool = True,
        emit_mock_returns: bool = True,
    ):
        self.project_dir = Path(project_dir)
        self.rte_header = rte_header
        self.emit_call_counters = emit_call_counters
        self.emit_mock_returns = emit_mock_returns

        # Tracks generated modules to avoid re-generating
        self._generated: Set[str] = set()

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def generate(self, swc: SWCComponent) -> StubModule:
        """Generate stub files for a single SWC component.

        Args:
            swc: Parsed SWC component descriptor.

        Returns:
            StubModule descriptor with generated file paths.
        """
        if swc.short_name in self._generated:
            log.debug("SWC '%s' already generated, skipping", swc.short_name)
            module = self._build_stub_module(swc)
            return module

        module = self._build_stub_module(swc)
        self._write_stub_files(swc, module)
        self._generated.add(swc.short_name)
        log.info(
            "Generated stubs for SWC '%s': %d functions, %d ports",
            swc.short_name,
            len(module.functions),
            len(swc.ports),
        )
        return module

    def generate_all(self, swcs: List[SWCComponent]) -> Dict[str, StubModule]:
        """Generate stub files for multiple SWC components.

        Args:
            swcs: List of SWCComponent instances.

        Returns:
            Dict mapping SWC short names to their StubModule.
        """
        results: Dict[str, StubModule] = {}
        for swc in swcs:
            module = self.generate(swc)
            results[swc.short_name] = module
        return results

    def clear(self) -> None:
        """Reset the generated set (useful for re-generation)."""
        self._generated.clear()

    # ------------------------------------------------------------------
    # Module construction
    # ------------------------------------------------------------------

    def _build_stub_module(self, swc: SWCComponent) -> StubModule:
        """Build a StubModule descriptor for the given SWC."""
        module = StubModule(
            swc_name=swc.short_name,
            header_path=f"{DEFAULT_SWC_DIR}/{swc.short_name.lower()}/{swc.short_name}_Stub.h",
            source_path=f"{DEFAULT_SWC_DIR}/{swc.short_name.lower()}/{swc.short_name}_Stub.c",
            includes=[self.rte_header],
        )

        # 1. Generate RTE read/write stubs for each port
        for port in swc.ports:
            if port.direction == "in":
                stub = self._make_rte_read_stub(port)
                module.functions.append(stub)
                module.rte_reads.append(port.short_name)
            elif port.direction == "out":
                stub = self._make_rte_write_stub(port)
                module.functions.append(stub)
                module.rte_writes.append(port.short_name)

        # 2. Generate runnable entity stubs
        for runnable in swc.runnables:
            stub = self._make_runnable_stub(runnable, swc)
            module.functions.append(stub)

        # 3. Generate global variables (call counters, mock returns)
        module.global_vars = self._make_global_vars(module)

        return module

    # ------------------------------------------------------------------
    # RTE primitive stubs
    # ------------------------------------------------------------------

    def _make_rte_read_stub(self, port: PortPrototype) -> StubFunction:
        """Create a StubFunction for Rte_Read on a receiver port."""
        port_lower = port.short_name[0].lower() + port.short_name[1:]
        data_type = self._port_data_type(port)

        func_name = f"{RTE_READ_MACRO}_{port_lower}"
        params = [f"{data_type}* value"]

        body = [
            f"/* Stub: RTE read from port '{port.short_name}' */",
            f"*value = _{port_lower}_mock_value;",
            f"_{port_lower}_call_count++;",
            "return RTE_E_OK;",
        ]

        return StubFunction(
            name=func_name,
            return_type="Std_ReturnType",
            params=params,
            call_counter=True,
            comment=f"Stub RTE read for receiver port '{port.short_name}'.",
            is_rte_primitive=True,
            body_lines=body,
        )

    def _make_rte_write_stub(self, port: PortPrototype) -> StubFunction:
        """Create a StubFunction for Rte_Write on a sender port."""
        port_lower = port.short_name[0].lower() + port.short_name[1:]
        data_type = self._port_data_type(port)

        func_name = f"{RTE_WRITE_MACRO}_{port_lower}"
        params = [f"const {data_type} value"]

        body = [
            f"/* Stub: RTE write to port '{port.short_name}' */",
            f"_{port_lower}_last_value = value;",
            f"_{port_lower}_call_count++;",
            "return RTE_E_OK;",
        ]

        return StubFunction(
            name=func_name,
            return_type="Std_ReturnType",
            params=params,
            call_counter=True,
            comment=f"Stub RTE write for sender port '{port.short_name}'.",
            is_rte_primitive=True,
            body_lines=body,
        )

    # ------------------------------------------------------------------
    # Runnable entity stubs
    # ------------------------------------------------------------------

    def _make_runnable_stub(self, runnable: RunnableEntity, swc: SWCComponent) -> StubFunction:
        """Create a stub function for a RunnableEntity."""
        symbol = runnable.symbol or runnable.short_name
        period_info = f" (period: {runnable.period_ms}ms)" if runnable.period_ms else ""

        body = [
            f"/* Stub: Runnable '{runnable.short_name}'{period_info} */",
        ]

        # Add RTE reads
        for port_name in runnable.data_read_access:
            body.append(f"    /* Would read from port: {port_name} */")

        # Add RTE writes
        for port_name in runnable.data_write_access:
            body.append(f"    /* Would write to port: {port_name} */")

        # Add server calls
        for scp in runnable.server_call_points:
            body.append(f"    /* Would call server: {scp} */")

        body.append(f"    _{runnable.short_name}_call_count++;")

        comment = (
            f"Stub for runnable '{runnable.short_name}'."
            f"{period_info}"
        )
        if runnable.can_be_invoked_concurrently:
            comment += " Supports concurrent invocation."

        return StubFunction(
            name=symbol,
            return_type="void",
            params=[],
            call_counter=True,
            comment=comment,
            body_lines=body,
        )

    # ------------------------------------------------------------------
    # Global variable generation
    # ------------------------------------------------------------------

    def _make_global_vars(self, module: StubModule) -> List[str]:
        """Generate global variable declarations for the stub module."""
        vars: List[str] = []

        for func in module.functions:
            if func.call_counter and self.emit_call_counters:
                vars.append(
                    f"static volatile uint32 _{func.name}_call_count = 0U;"
                )

        for port_name in module.rte_reads:
            dt = "uint8"  # default data type
            vars.append(f"static {dt} _{port_name}_mock_value = 0U;")

        for port_name in module.rte_writes:
            dt = "uint8"
            vars.append(f"static {dt} _{port_name}_last_value = 0U;")

        return vars

    # ------------------------------------------------------------------
    # File writing
    # ------------------------------------------------------------------

    def _write_stub_files(self, swc: SWCComponent, module: StubModule) -> None:
        """Write stub header and source files to disk."""
        swc_dir = swc.short_name.lower()
        out_dir = self.project_dir / DEFAULT_SWC_DIR / swc_dir
        out_dir.mkdir(parents=True, exist_ok=True)

        header_path = out_dir / f"{swc.short_name}_Stub.h"
        source_path = out_dir / f"{swc.short_name}_Stub.c"

        header_content = self._render_header(swc, module)
        source_content = self._render_source(swc, module)

        header_path.write_text(header_content, encoding="utf-8")
        source_path.write_text(source_content, encoding="utf-8")

        # Also create test harness
        test_dir = self.project_dir / DEFAULT_TEST_DIR / swc_dir
        test_dir.mkdir(parents=True, exist_ok=True)
        test_path = test_dir / f"test_{swc.short_name}_stubs.c"
        test_content = self._render_test_harness(swc, module)
        test_path.write_text(test_content, encoding="utf-8")

        # Create mock support file
        mock_dir = self.project_dir / DEFAULT_MOCK_DIR / swc_dir
        mock_dir.mkdir(parents=True, exist_ok=True)
        mock_path = mock_dir / f"mock_{swc.short_name}.h"
        mock_content = self._render_mock_header(swc, module)
        mock_path.write_text(mock_content, encoding="utf-8")

    # ------------------------------------------------------------------
    # Rendering
    # ------------------------------------------------------------------

    def _render_header(self, swc: SWCComponent, module: StubModule) -> str:
        """Render the stub header file."""
        guard = HEADER_GUARD_TEMPLATE.format(name=swc.short_name.upper())

        lines: List[str] = [
            self._license_block(swc.arxml_file),
            f"#ifndef {guard}",
            f"#define {guard}",
            "",
            "#ifdef __cplusplus",
            'extern "C" {',
            "#endif",
            "",
            "/* ================================================================ */",
            f"/*  Stub Header — {swc.short_name}                                  */",
            "/* ================================================================ */",
            "",
        ]

        # Includes
        for inc in module.includes:
            lines.append(f"#include {inc}")
        lines.append("")

        # Std types
        lines.append("#ifndef RTE_E_OK")
        lines.append("#define RTE_E_OK      0U")
        lines.append("#define RTE_E_INVALID 1U")
        lines.append("#endif")
        lines.append("")

        # Global externs for test access
        lines.append("/* ======== Mock control variables ======== */")
        for func in module.functions:
            if func.call_counter:
                lines.append(f"extern volatile uint32 _{func.name}_call_count;")
        for port_name in module.rte_reads:
            lines.append(f"extern uint8 _{port_name}_mock_value;")
        for port_name in module.rte_writes:
            lines.append(f"extern uint8 _{port_name}_last_value;")
        lines.append("")

        # Function declarations
        lines.append("/* ======== Stub function prototypes ======== */")
        for func in module.functions:
            if func.comment:
                lines.append(f"/** {func.comment} */")
            params_str = ", ".join(func.params)
            lines.append(f"{func.return_type} {func.name}({params_str});")
            lines.append("")

        lines.append("#ifdef __cplusplus")
        lines.append("}")
        lines.append("#endif")
        lines.append("")
        lines.append(f"#endif /* {guard} */")
        lines.append("")

        return "\n".join(lines)

    def _render_source(self, swc: SWCComponent, module: StubModule) -> str:
        """Render the stub source file."""
        lines: List[str] = [
            self._license_block(swc.arxml_file),
            f'#include "{swc.short_name}_Stub.h"',
            "",
            "/* ================================================================ */",
            f"/*  Stub Source — {swc.short_name}                                   */",
            "/* ================================================================ */",
            "",
        ]

        # Global variables (internally linked)
        lines.append("/* ======== Internal mock state ======== */")
        for var in module.global_vars:
            lines.append(var)
        lines.append("")

        # Function implementations
        lines.append("/* ======== Stub implementations ======== */")
        for func in module.functions:
            if func.comment:
                lines.append(f"/* {func.comment} */")
            params_str = ", ".join(func.params)
            lines.append(f"{func.return_type} {func.name}({params_str})")
            lines.append("{")

            if func.body_lines:
                for body_line in func.body_lines:
                    lines.append(f"    {body_line}")
            else:
                # Default body
                if func.call_counter:
                    lines.append(f"    _{func.name}_call_count++;")
                if func.return_type != "void":
                    lines.append(f"    return ({func.return_type})0U;")

            lines.append("}")
            lines.append("")

        return "\n".join(lines)

    def _render_test_harness(self, swc: SWCComponent, module: StubModule) -> str:
        """Render a minimal test harness for the stub module."""
        lines: List[str] = [
            self._license_block(swc.arxml_file),
            "#include \"unity.h\"",
            f'#include "{swc.short_name}_Stub.h"',
            "",
            "/* ================================================================ */",
            f"/*  Test Harness — {swc.short_name} Stubs                            */",
            "/* ================================================================ */",
            "",
            "void setUp(void) {",
            "    /* Reset all mock state */",
        ]

        # Reset counters
        for func in module.functions:
            if func.call_counter:
                lines.append(f"    _{func.name}_call_count = 0U;")
        for port_name in module.rte_reads:
            lines.append(f"    _{port_name}_mock_value = 0U;")
        for port_name in module.rte_writes:
            lines.append(f"    _{port_name}_last_value = 0U;")
        lines.append("}")
        lines.append("")

        lines.append("void tearDown(void) {")
        lines.append("}")
        lines.append("")

        # Generate basic tests
        lines.append("/* ======== Stub smoke tests ======== */")
        for func in module.functions:
            func_name = func.name
            lines.append(f"void test_{func_name}_can_be_called(void)")
            lines.append("{")
            params_call = ", ".join(
                [f"({p.split(' ')[0]})0U" if p.startswith("const") else "0U" for p in func.params]
            ) if func.params else ""
            lines.append(f"    {func_name}({params_call});")
            if func.call_counter:
                lines.append(f"    TEST_ASSERT_EQUAL(1, _{func_name}_call_count);")
            lines.append("}")
            lines.append("")

        lines.append("/* ======== Test runner ======== */")
        lines.append("int main(void)")
        lines.append("{")
        lines.append("    UNITY_BEGIN();")
        for func in module.functions:
            lines.append(f'    RUN_TEST(test_{func.name}_can_be_called);')
        lines.append("    return UNITY_END();")
        lines.append("}")

        return "\n".join(lines)

    def _render_mock_header(self, swc: SWCComponent, module: StubModule) -> str:
        """Render a mock helper header for test configuration."""
        guard = f"{swc.short_name.upper()}_MOCK_H_"

        lines: List[str] = [
            self._license_block(swc.arxml_file),
            f"#ifndef {guard}",
            f"#define {guard}",
            "",
            "#ifdef __cplusplus",
            'extern "C" {',
            "#endif",
            "",
            "/* ================================================================ */",
            f"/*  Mock Helpers — {swc.short_name}                                    */",
            "/* ================================================================ */",
            "",
            f'#include "{swc.short_name}_Stub.h"',
            "",
            "/* ======== Mock setup helpers ======== */",
            "",
            "/** Reset all mock state for this SWC. */",
            "static inline void mock_reset(void)",
            "{",
        ]

        for func in module.functions:
            if func.call_counter:
                lines.append(f"    _{func.name}_call_count = 0U;")
        for port_name in module.rte_reads:
            lines.append(f"    _{port_name}_mock_value = 0U;")
        for port_name in module.rte_writes:
            lines.append(f"    _{port_name}_last_value = 0U;")
        lines.append("}")
        lines.append("")

        # Mock value setters
        for port_name in module.rte_reads:
            lines.append(f"static inline void mock_set_{port_name}(uint8 value)")
            lines.append("{")
            lines.append(f"    _{port_name}_mock_value = value;")
            lines.append("}")
            lines.append("")

        # Value getters
        for port_name in module.rte_writes:
            lines.append(f"static inline uint8 mock_get_{port_name}(void)")
            lines.append("{")
            lines.append(f"    return _{port_name}_last_value;")
            lines.append("}")
            lines.append("")

        # Call count accessors
        for func in module.functions:
            if func.call_counter:
                lines.append(f"static inline uint32 mock_{func.name}_call_count(void)")
                lines.append("{")
                lines.append(f"    return _{func.name}_call_count;")
                lines.append("}")
                lines.append("")

        lines.append("#ifdef __cplusplus")
        lines.append("}")
        lines.append("#endif")
        lines.append("")
        lines.append(f"#endif /* {guard} */")
        lines.append("")

        return "\n".join(lines)

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _port_data_type(port: PortPrototype) -> str:
        """Determine the C data type for a port (heuristic)."""
        iface_lower = port.interface_ref.lower()
        if "bool" in iface_lower or "flag" in iface_lower:
            return "boolean"
        if "uint8" in iface_lower or "u8" in iface_lower:
            return "uint8"
        if "uint16" in iface_lower or "u16" in iface_lower:
            return "uint16"
        if "uint32" in iface_lower or "u32" in iface_lower:
            return "uint32"
        if "sint8" in iface_lower or "s8" in iface_lower:
            return "sint8"
        if "sint16" in iface_lower or "s16" in iface_lower:
            return "sint16"
        if "sint32" in iface_lower or "s32" in iface_lower:
            return "sint32"
        if "float" in iface_lower:
            return "float32"
        return "uint8"  # safe default

    def _license_block(self, source: str) -> str:
        """Render the license/copyright header block."""
        from datetime import datetime
        return LICENSE_BLOCK.format(
            source=source or "unknown",
            timestamp=datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        )


# ---------------------------------------------------------------------------
# CLI integration
# ---------------------------------------------------------------------------


def generate_stubs(
    arxml_path: str,
    output_dir: str = "generated/stubs",
    swc_filter: str = "",
) -> Dict[str, StubModule]:
    """Generate stubs from an ARXML file.

    This is the entry point called by ``yuleosh autosar gen-stub``.

    Args:
        arxml_path: Path to the ARXML file.
        output_dir: Output directory for generated files.
        swc_filter: Optional SWC name filter (generates only matching SWC).

    Returns:
        Dict mapping SWC short names to their StubModule descriptors.
    """
    from yuleosh.autosar.parser import ARXMLParser

    parser = ARXMLParser()
    swcs = parser.parse_swc(arxml_path)

    if swc_filter:
        swcs = [s for s in swcs if s.short_name == swc_filter]
        if not swcs:
            log.warning("SWC '%s' not found in %s", swc_filter, arxml_path)
            return {}

    gen = StubGenerator(project_dir=output_dir)
    results = gen.generate_all(swcs)

    # Print summary
    print(f"\n  📦 AUTOSAR Stub Generation Summary")
    print(f"  {'=' * 45}")
    for swc_name, module in results.items():
        print(f"  ✅ {swc_name}: {len(module.functions)} stubs")
        print(f"     └─ {module.header_path}")
        print(f"     └─ {module.source_path}")
    print(f"\n  Total SWCs: {len(results)}")
    print(f"  Output:     {Path(output_dir).resolve()}")
    print()

    return results


def register_cli(subparsers) -> None:
    """Register the ``autosar gen-stub`` subcommand on the given subparsers group.

    Designed to be called from the yuleOSH CLI's main parser setup::

        # In yuleosh_cli.py's _build_parser() or main():
        p_autosar = sub.add_parser("autosar", help="AUTOSAR management")
        asub = p_autosar.add_subparsers(dest="autosar_sub")
        from yuleosh.autosar.stubgen import register_cli
        register_cli(asub)
    """
    p_stub = subparsers.add_parser(
        "gen-stub",
        help="Generate RTE stub/mock code from ARXML",
        description="Parse AUTOSAR ARXML and generate C stub/mock files "
                    "for runnable entities and RTE port primitives.",
    )
    p_stub.add_argument(
        "arxml",
        type=str,
        help="Path to the ARXML file",
    )
    p_stub.add_argument(
        "--output", "-o",
        type=str,
        default="generated/stubs",
        help="Output directory (default: generated/stubs)",
    )
    p_stub.add_argument(
        "--swc",
        type=str,
        default="",
        help="Generate stubs for a specific SWC only",
    )
    p_stub.add_argument(
        "--verbose", "-v",
        action="store_true",
        help="Verbose output",
    )
    p_stub.set_defaults(func=_handle_gen_stub_command)


def _handle_gen_stub_command(args) -> None:
    """Handle the ``yuleosh autosar gen-stub`` CLI command."""
    import sys
    from pathlib import Path

    arxml_path = Path(args.arxml)
    if not arxml_path.exists():
        print(f"Error: file not found: {arxml_path}", file=sys.stderr)
        sys.exit(1)

    if args.verbose:
        logging.getLogger("autosar.stubgen").setLevel(logging.DEBUG)

    try:
        generate_stubs(
            arxml_path=str(arxml_path),
            output_dir=args.output,
            swc_filter=args.swc,
        )
    except Exception as e:
        print(f"Error generating stubs: {e}", file=sys.stderr)
        sys.exit(1)
