#!/usr/bin/env python3
# Copyright (c) 2025 frisky1985
# SPDX-License-Identifier: Elastic-2.0
"""Codegen: 从后端角色契约生成前端类型与镜像 JSON（role drift CI guard）。

单一事实来源：src/yuleosh/rbac/role_contract.py
生成物（均提交到仓库，CI 校验与源一致）：
  - frontend/src/lib/role-contract.generated.ts  （OrgRole union + ROLE_TIER/ROLE_UI_VIEW 常量）
  - role_contract.json                           （人类可读镜像，供后端/前端契约测试校验）

用法：npm run gen:role-contract  （frontend predev/prebuild 自动调用）
"""

import json
import os
import sys
from pathlib import Path

# codegen 是构建期工具，仅需读取后端契约；auth_extended 在导入链上会校验
# YULEOSH_JWT_SECRET，这里设一个 dummy 值让导入链通过（不参与任何运行期逻辑）。
os.environ.setdefault("YULEOSH_JWT_SECRET", "codegen-dummy-not-for-production")

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))

from yuleosh.rbac.role_contract import (  # noqa: E402
    ALL_ORG_ROLES,
    ROLE_TO_TIER,
    ROLE_TO_UI_VIEW,
    ROLE_LEGACY,
)


def render_ts() -> str:
    """Render the generated TypeScript contract module."""
    org_roles = " | ".join(f'"{r}"' for r in ALL_ORG_ROLES)
    tier_entries = ",\n".join(f"  {r!r}: {t!r}" for r, t in ROLE_TO_TIER.items())
    ui_entries = ",\n".join(
        f'  {r!r}: "engineer"' if v == "engineer" else f'  {r!r}: "decision"'
        for r, v in ROLE_TO_UI_VIEW.items()
    )
    return (
        "// AUTO-GENERATED by scripts/gen_role_contract.py — DO NOT EDIT BY HAND.\n"
        "// 单一事实来源：src/yuleosh/rbac/role_contract.py\n"
        "// 改角色契约请改后端契约文件后重跑 codegen（npm run gen:role-contract）。\n"
        "// CI 会校验本文件与源契约一致，不一致则构建失败。\n\n"
        f"export type OrgRole =\n  | {org_roles};\n\n"
        'export type UiView = "decision" | "engineer";\n\n'
        "export const ROLE_TIER: Record<OrgRole, string> = {\n"
        f"{tier_entries},\n"
        "};\n\n"
        'export const ROLE_UI_VIEW: Record<string, UiView> = {\n'
        f"{ui_entries},\n"
        "};\n"
    )


def render_json() -> str:
    """Render the human-readable JSON mirror of the contract."""
    roles = {
        r: {
            "permission_tier": ROLE_TO_TIER[r],
            "ui_view": ROLE_TO_UI_VIEW[r],
            "legacy": r in ROLE_LEGACY,
        }
        for r in ALL_ORG_ROLES
    }
    contract = {
        "version": 1,
        "description": (
            "角色 → 权限档 → UI 视图 的单一事实来源镜像。真实 SSOT 为后端 "
            "src/yuleosh/rbac/role_contract.py，本文件由 scripts/gen_role_contract.py 生成，"
            "供后端 test_role_contract.py 与前端 role-view.test.ts 双向校验。改任一角色映射"
            "必须先改后端契约并重跑 codegen，否则对应测试变红。"
        ),
        "roles": roles,
    }
    return json.dumps(contract, ensure_ascii=False, indent=2) + "\n"


def main() -> None:
    ts_path = ROOT / "frontend" / "src" / "lib" / "role-contract.generated.ts"
    json_path = ROOT / "role_contract.json"
    ts_path.write_text(render_ts(), encoding="utf-8")
    json_path.write_text(render_json(), encoding="utf-8")
    print(f"generated {ts_path}")
    print(f"generated {json_path}")


if __name__ == "__main__":
    main()
