/**
 * @file Mcu_Cfg.h
 * @brief MCU Driver Configuration — S32K312.
 *
 * Configuration option set for the yuleASR MCU driver.
 * Generated by yuleASR configurator tool.
 * Edit manually or use yule-configurator for GUI-based config.
 */

#ifndef MCU_CFG_H
#define MCU_CFG_H

/* ─── Clock Configuration ─────────────────────────────────── */

#define MCU_CLOCK_SOURCE            MCU_CLOCK_SOURCE_PLL
#define MCU_PLL_REF_CLOCK_HZ        8000000UL     /* 8 MHz external OSC */
#define MCU_CORE_CLOCK_HZ           120000000UL   /* 120 MHz core */
#define MCU_BUS_CLOCK_HZ            60000000UL    /* 60 MHz bus */
#define MCU_SYS_CLOCK_HZ            120000000UL   /* 120 MHz system */

/* ─── Reset Configuration ─────────────────────────────────── */

#define MCU_RESET_DETECTION_ENABLE  STD_ON
#define MCU_WATCHDOG_DISABLE        STD_ON   /* Disable WDOG before init */

/* ─── RAM Sector Configuration ────────────────────────────── */

#define MCU_RAM_SECTIONS            2
#define MCU_RAM_SECTION_0_START     0x1FFF8000UL
#define MCU_RAM_SECTION_0_SIZE      0x10000UL   /* 64 KB SRAM_L */
#define MCU_RAM_SECTION_1_START     0x20008000UL
#define MCU_RAM_SECTION_1_SIZE      0x10000UL   /* 64 KB SRAM_U */

/* ─── Version Info ─────────────────────────────────────────── */

#define MCU_VENDOR_ID                0x00FF    /* yuleASR vendor ID */
#define MCU_MODULE_ID                0x00      /* AUTOSAR Mcu module ID */
#define MCU_SW_MAJOR_VERSION         1
#define MCU_SW_MINOR_VERSION         0
#define MCU_SW_PATCH_VERSION         0

/* ─── Configuration Set ───────────────────────────────────── */

typedef struct {
    uint32_t coreClockHz;
    uint32_t busClockHz;
    uint32_t sysClockHz;
    uint8_t  pllRefDiv;
    uint8_t  pllMulFactor;
    uint8_t  pllPreDiv;
} Mcu_ConfigType;

extern const Mcu_ConfigType McuConfig;

#endif /* MCU_CFG_H */
