#!/usr/bin/env python3
# Copyright (c) 2025 frisky1985
# SPDX-License-Identifier: MIT

"""
CI Stages — Traceability stage execution functions.

Part of the stages/ package split from stages.py.
"""

#!/usr/bin/env python3
# Copyright (c) 2025 frisky1985
# SPDX-License-Identifier: MIT

"""
CI Stages — individual CI stage execution functions.

Each function runs one CI check (lint, coverage, etc.).
Called by layers.py to compose full CI layers.
"""

import fnmatch
import json
import logging
import os
import subprocess
import sys
import time
from datetime import datetime
from pathlib import Path
from typing import Optional

from yuleosh.ci.config import is_strict, is_misra_fail_fast, _get_ci_config
from yuleosh.ci.result import CIResult, timed_stage

from yuleosh.ci.stage_utils import (
    find_test_files, get_cache_key_for_dir,
    _test_file_cache, _test_file_cache_mtime,
    _should_skip_coverage, _coverage_skip_reason,
    _run_coverage_and_export, _load_coverage_json,
    _resolve_cross_compile, _cross_compile_via_docker,
    _handle_stage_error, _run_subprocess,
)

log = logging.getLogger("ci.stages")



def run_requirements_trace(project_dir: str, ci: CIResult) -> bool:
    """Check basic requirements traceability (SWE.5 left side).

    Verifies that requirements in spec.md have corresponding code
    modules or test files.  This is a lightweight left-side check;
    full LRM/LRT is generated by the traceability command.
    """
    print("  🔗 CI: requirements trace check (SWE.5 V-Model left side)...")

    specs_dir = Path(project_dir) / "specs"
    docs_dir = Path(project_dir) / "docs"

    # Count SHALL statements in spec files
    req_count = 0
    keywords_found = []
    for spec_file in list(specs_dir.glob("*.md")) + list(docs_dir.glob("*.md")):
        content = spec_file.read_text(errors="replace")
        shall_count = content.count("SHALL")
        if shall_count > 0:
            req_count += shall_count
            keywords_found.append(f"{spec_file.name}: {shall_count}")

    # Estimate code coverage by module files
    code_dir = Path(project_dir) / "src" / "yuleosh"
    py_files = list(code_dir.rglob("*.py")) if code_dir.exists() else []
    test_dir = Path(project_dir) / "tests"
    test_files = list(test_dir.rglob("test_*.py")) if test_dir.exists() else []

    code_to_test_ratio = len(test_files) / max(len(py_files), 1)
    trace_score = min(100, int(code_to_test_ratio * 100))

    ci.add_stage("requirements-trace", "passed",
                 f"{req_count} reqs, {len(py_files)} modules, "
                 f"{len(test_files)} tests (ratio {code_to_test_ratio:.1%})")
    print(f"    ✅ Requirements trace: {req_count} reqs, "
          f"{len(py_files)} modules, {len(test_files)} tests")
    return True


# ═══════════════════════════════════════════════════════════════════════
# H-07: Code↔Doc Sync Gate CI Integration
# ═══════════════════════════════════════════════════════════════════════

