// AUTO-GENERATED by scripts/gen_role_contract.py — DO NOT EDIT BY HAND.
// 单一事实来源：src/yuleosh/rbac/role_contract.py
// 改角色契约请改后端契约文件后重跑 codegen（npm run gen:role-contract）。
// CI 会校验本文件与源契约一致，不一致则构建失败。

export type OrgRole =
  | "owner" | "admin" | "quality_manager" | "architect" | "developer" | "reviewer" | "auditor" | "viewer" | "member";

export type UiView = "decision" | "engineer";

export const ROLE_TIER: Record<OrgRole, string> = {
  'owner': 'admin',
  'admin': 'admin',
  'architect': 'developer',
  'developer': 'developer',
  'reviewer': 'reviewer',
  'auditor': 'auditor',
  'member': 'developer',
  'quality_manager': 'quality_manager',
  'viewer': 'viewer',
};

export const ROLE_UI_VIEW: Record<string, UiView> = {
  'owner': "decision",
  'admin': "decision",
  'architect': "engineer",
  'developer': "engineer",
  'reviewer': "engineer",
  'auditor': "engineer",
  'member': "engineer",
  'quality_manager': "engineer",
  'viewer': "engineer",
};
